server:
  port: 8790
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8 #Default: UTF-8
      enabled: true #Default: true
  application:
    name: service-zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@192.168.1.101:8761/eureka/
  instance:
    hostname: 192.168.1.101
    ip-address: 192.168.1.101 #强制指定IP地址，默认会获取本机的IP地址
    instance-id: ${spring.application.name}:${server.port} #服务中心的信息显示（如果IP地址不显示的话，进行配置）
    prefer-ip-address: true #以IP地址注册到服务中心
    
zuul:
  routes:
    api-a:
      path: /api-config-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-config-b/**
      serviceId: service-feign